### ISSUE TITLE
CRITICAL: TypeError: object of type 'NoneType' has no len()

### ISSUE THREAD

**Issue by Zercerium** [KLIMA-WH/adois_app#1]
Hello I try to use your Docker setup, sadly it fails with the following message and the output folder stays empty.

```
...
INFO: Iteration 19/19 -> tile cached
INFO: Cached geodataframes concatenated
INFO: Geodataframe postprocessed (sieved and filled)
INFO: Geodataframe postprocessed (simplified)
INFO: Grid 1/2 created
INFO: Grid 2/2 created
CRITICAL: TypeError: object of type 'NoneType' has no len()
```

Any suggestions how to solve this problem? If you need further information, please ask.

**Comment by mrsmrynk** [comment]
Hey, I assume that you're not using the `shape_file_path` parameter in your config file. The resulting error message is from a known bug, I will fix it soon.

---

**Workaround:**
Please use

```yaml
aggregation:
  tile_size:
    - 50
    - 100
  shape_file_path:  # this is currently mandatory
```

in your config file and rerun the container. This should work for now.

**Comment by Zercerium** [comment]
thanks a lot, workaround worked.
