### ISSUE TITLE
the train dataset

### ISSUE THREAD

**Issue by zhongxia777** [KLIMA-WH/adois_app#2]
Which dataset you guys are training on, I want to train again :)

**Comment by mrsmrynk** [comment]
Hey, the dataset used to train the model is derived from proprietary data provided by our project partner, so unfortunately we're not authorized to share it.

But you can have a look at ISPRS's [2D Semantic Labeling Contest](https://www.isprs.org/education/benchmarks/UrbanSemLab/default.aspx) and their Potsdam and Vaihingen datasets for similar data.
